; Weapon balance overhaul
filterByKeywords=WeaponTypeBow,WeapMaterialImperial:attackDamage=30
filterByKeywordsOr=WeaponTypeSword,WeaponTypeWarAxe:attackDamage=25:speed=1.1
filterByKeywords=WeaponTypeBow:filterByKeywordsExcluded=WeapMaterialDaedric:attackDamage=18
