; Armor keyword standardization
filterByKeywords=ArmorHeavy:keywordsToAdd=MyHeavyTag,ArmorMaterialIron
filterByKeywords=ArmorLight:keywordsToAdd=MyLightTag
filterByKeywords=ArmorHeavy:damageResist=50:weight=20:value=150
