// GENERATED FILE — DO NOT EDIT BY HAND.
// Source: data/relations/*.yaml
// Regenerate with: python3 tools/gen_relations.py

#include "mora/model/relations.h"
#include "mora/model/validate.h"

namespace mora::model {

constexpr RelationEntry kRelations[] = {
    // ── form/* ──
    {
        .namespace_ = "form",
        .name = "npc",
        .args = {{ElemType::FormRef, "F"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = ""},
        .docs = "True when F is a base NPC record.",
    },
    {
        .namespace_ = "form",
        .name = "weapon",
        .args = {{ElemType::FormRef, "F"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "WEAP", .subrecord = ""},
        .docs = "True when F is a weapon base record.",
    },
    {
        .namespace_ = "form",
        .name = "armor",
        .args = {{ElemType::FormRef, "F"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "ARMO", .subrecord = ""},
        .docs = "True when F is an armor base record.",
    },
    {
        .namespace_ = "form",
        .name = "keyword",
        .args = {{ElemType::FormRef, "F"}, {ElemType::FormRef, "KW"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "", .subrecord = "KWDA"},
        .docs = "Keyword membership on a base record (body: query; head: add/remove).",
    },
    {
        .namespace_ = "form",
        .name = "faction",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::FormRef, "FAC"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "SNAM"},
        .docs = "Faction membership on an NPC base record.",
    },
    {
        .namespace_ = "form",
        .name = "damage",
        .args = {{ElemType::FormRef, "W"}, {ElemType::Int, "N"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "WEAP", .subrecord = "DNAM"},
        .docs = "Weapon base damage.",
    },
    {
        .namespace_ = "form",
        .name = "gold_value",
        .args = {{ElemType::FormRef, "F"}, {ElemType::Int, "N"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "", .subrecord = "DATA"},
        .docs = "Gold value of an item.",
    },
    {
        .namespace_ = "form",
        .name = "name",
        .args = {{ElemType::FormRef, "F"}, {ElemType::String, "S"}},
        .arg_count = 2,
        .type = {TypeCtor::Scalar, ElemType::String},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "", .subrecord = "FULL"},
        .docs = "Display name.",
    },
    {
        .namespace_ = "form",
        .name = "base_level",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::Int, "L"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "ACBS"},
        .docs = "NPC base level.",
    },
    {
        .namespace_ = "form",
        .name = "race",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::FormRef, "RACE"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "RNAM"},
        .docs = "NPC base race.",
    },
    // ── ref/* ──
    {
        .namespace_ = "ref",
        .name = "keyword",
        .args = {{ElemType::FormRef, "R"}, {ElemType::FormRef, "KW"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Handler,
        .apply_handler = HandlerId::RefAddKeyword,
        .retract_handler = HandlerId::RefRemoveKeyword,
        .docs = "Keywords added dynamically to a specific placed reference.",
    },
    {
        .namespace_ = "ref",
        .name = "current_location",
        .args = {{ElemType::FormRef, "R"}, {ElemType::FormRef, "LOC"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Handler,
        .docs = "The location this reference is currently in.",
    },
    {
        .namespace_ = "ref",
        .name = "base_form",
        .args = {{ElemType::FormRef, "R"}, {ElemType::FormRef, "F"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Handler,
        .docs = "Bridge from live reference to its base record.",
    },
    {
        .namespace_ = "ref",
        .name = "in_combat",
        .args = {{ElemType::FormRef, "R"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Handler,
        .docs = "True when this reference is currently in combat.",
    },
    // ── player/* ──
    {
        .namespace_ = "player",
        .name = "gold",
        .args = {{ElemType::FormRef, "P"}, {ElemType::Int, "N"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Int},
        .source = RelationSourceKind::Handler,
        .apply_handler = HandlerId::PlayerAddGold,
        .docs = "Player gold count (additive delta via 'add').",
    },
    {
        .namespace_ = "player",
        .name = "notification",
        .args = {{ElemType::FormRef, "P"}, {ElemType::String, "S"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::String},
        .source = RelationSourceKind::Handler,
        .apply_handler = HandlerId::PlayerShowNotification,
        .docs = "Queue a UI notification string.",
    },
    // ── world/* ──
    {
        .namespace_ = "world",
        .name = "time_of_day",
        .args = {{ElemType::Float, "T"}},
        .arg_count = 1,
        .type = {TypeCtor::Const, ElemType::Float},
        .source = RelationSourceKind::Hook,
        .hook = {.hook_name = "OnTimeOfDayChanged", .kind = HookSpec::Kind::State},
        .docs = "Current in-game hour 0..24.",
    },
    // ── event/* ──
    {
        .namespace_ = "event",
        .name = "entered_location",
        .args = {{ElemType::FormRef, "R"}, {ElemType::FormRef, "LOC"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Event,
        .hook = {.hook_name = "OnLocationChange", .kind = HookSpec::Kind::Edge},
        .docs = "Fires when a reference enters a new location.",
    },
    {
        .namespace_ = "event",
        .name = "combat_state_changed",
        .args = {{ElemType::FormRef, "R"}, {ElemType::Int, "STATE"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::Int},
        .source = RelationSourceKind::Event,
        .hook = {.hook_name = "OnCombatStateChanged", .kind = HookSpec::Kind::Edge},
        .docs = "Fires on combat state transitions.",
    },
};

const size_t kRelationCount = sizeof(kRelations) / sizeof(kRelations[0]);

static_assert(validate_all(kRelations, sizeof(kRelations) / sizeof(kRelations[0])),
              "kRelations fails validation — see helper checks");

} // namespace mora::model
