// GENERATED FILE — DO NOT EDIT BY HAND.
// Source: data/relations/**/*.yaml
// Regenerate with: python3 tools/gen_relations.py

#include "mora/model/relations.h"
#include "mora/model/validate.h"

namespace mora::model {

constexpr RelationEntry kRelations[] = {
    // ── form/* ──
    //   from data/relations/form/armor.yaml
    {
        .namespace_ = "form",
        .name = "armor",
        .args = {{ElemType::FormRef, "F"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "ARMO", .subrecord = ""},
        .docs = "True when F is an armor base record.",
    },
    {
        .namespace_ = "form",
        .name = "armor_rating",
        .args = {{ElemType::FormRef, "A"}, {ElemType::Float, "V"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Float},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "ARMO", .subrecord = "DNAM"},
        .docs = "Armor rating. Raw ESP value is the display rating × 100.",
    },
    //   from data/relations/form/leveled_list.yaml
    {
        .namespace_ = "form",
        .name = "leveled_list",
        .args = {{ElemType::FormRef, "F"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "LVLI", .subrecord = ""},
        .docs = "True when F is a Leveled Item list (registered via form_model.h).",
    },
    {
        .namespace_ = "form",
        .name = "leveled_char",
        .args = {{ElemType::FormRef, "F"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "LVLN", .subrecord = ""},
        .docs = "True when F is a Leveled Character list (registered via form_model.h).",
    },
    {
        .namespace_ = "form",
        .name = "chance_none",
        .args = {{ElemType::FormRef, "LIST"}, {ElemType::Int, "PCT"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "LVLI", .subrecord = "LVLD", .extract = EspExtract::Subrecord, .read_as = EspReadType::UInt8},
        .docs = "Percent chance (0..100) that a leveled list returns nothing.",
    },
    {
        .namespace_ = "form",
        .name = "leveled_entry",
        .args = {{ElemType::FormRef, "LIST"}, {ElemType::FormRef, "ENTRY"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "LVLI", .subrecord = "LVLO", .extract = EspExtract::ListField, .offset = 4, .read_as = EspReadType::FormID},
        .docs = "Leveled-item entries — the pool of references the list can produce. (Level and count are not captured yet.)",
    },
    //   from data/relations/form/npc.yaml
    {
        .namespace_ = "form",
        .name = "npc",
        .args = {{ElemType::FormRef, "F"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = ""},
        .docs = "True when F is a base NPC record.",
    },
    {
        .namespace_ = "form",
        .name = "base_level",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::Int, "L"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "ACBS"},
        .docs = "NPC base level.",
    },
    {
        .namespace_ = "form",
        .name = "calc_level_min",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::Int, "L"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "ACBS", .extract = EspExtract::PackedField, .offset = 10, .read_as = EspReadType::UInt16},
        .docs = "Minimum auto-calculated level for this NPC.",
    },
    {
        .namespace_ = "form",
        .name = "calc_level_max",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::Int, "L"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "ACBS", .extract = EspExtract::PackedField, .offset = 12, .read_as = EspReadType::UInt16},
        .docs = "Maximum auto-calculated level for this NPC (0 = no cap).",
    },
    {
        .namespace_ = "form",
        .name = "speed_mult",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::Int, "N"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "ACBS", .extract = EspExtract::PackedField, .offset = 14, .read_as = EspReadType::UInt16},
        .docs = "NPC movement speed multiplier (100 = normal).",
    },
    {
        .namespace_ = "form",
        .name = "race",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::FormRef, "RACE"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "RNAM"},
        .docs = "NPC base race.",
    },
    {
        .namespace_ = "form",
        .name = "npc_class",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::FormRef, "CLASS"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "CNAM", .extract = EspExtract::Subrecord, .read_as = EspReadType::FormID},
        .docs = "NPC class record (TESClass).",
    },
    {
        .namespace_ = "form",
        .name = "voice_type",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::FormRef, "VTYPE"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "VTCK", .extract = EspExtract::Subrecord, .read_as = EspReadType::FormID},
        .docs = "NPC voice type.",
    },
    {
        .namespace_ = "form",
        .name = "default_outfit",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::FormRef, "OUTFIT"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "DOFT", .extract = EspExtract::Subrecord, .read_as = EspReadType::FormID},
        .docs = "NPC default outfit (Outfit record).",
    },
    {
        .namespace_ = "form",
        .name = "female",
        .args = {{ElemType::FormRef, "NPC"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "ACBS", .extract = EspExtract::BitTest, .offset = 0, .bit = 0, .read_as = EspReadType::UInt32},
        .docs = "True when this NPC is female.",
    },
    {
        .namespace_ = "form",
        .name = "essential",
        .args = {{ElemType::FormRef, "NPC"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "ACBS", .extract = EspExtract::BitTest, .offset = 0, .bit = 1, .read_as = EspReadType::UInt32},
        .docs = "True when this NPC has the Essential flag (cannot be killed).",
    },
    {
        .namespace_ = "form",
        .name = "unique",
        .args = {{ElemType::FormRef, "NPC"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "ACBS", .extract = EspExtract::BitTest, .offset = 0, .bit = 5, .read_as = EspReadType::UInt32},
        .docs = "True when this NPC is marked Unique (only one instance can exist).",
    },
    {
        .namespace_ = "form",
        .name = "protected",
        .args = {{ElemType::FormRef, "NPC"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "ACBS", .extract = EspExtract::BitTest, .offset = 0, .bit = 11, .read_as = EspReadType::UInt32},
        .docs = "True when this NPC has the Protected flag (killable only by player).",
    },
    {
        .namespace_ = "form",
        .name = "spell",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::FormRef, "SPELL"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "SPLO", .extract = EspExtract::ListField, .element_size = 4, .read_as = EspReadType::FormID},
        .docs = "Spells granted to this NPC.",
    },
    {
        .namespace_ = "form",
        .name = "perk",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::FormRef, "PERK"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "PRKR", .extract = EspExtract::ListField, .element_size = 8, .read_as = EspReadType::FormID},
        .docs = "Perks granted to this NPC.",
    },
    {
        .namespace_ = "form",
        .name = "inventory_item",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::FormRef, "ITEM"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "CNTO", .extract = EspExtract::ListField, .element_size = 8, .read_as = EspReadType::FormID},
        .docs = "Items in this NPC's default inventory (CNTO is form+count).",
    },
    //   from data/relations/form/shared.yaml
    {
        .namespace_ = "form",
        .name = "keyword",
        .args = {{ElemType::FormRef, "F"}, {ElemType::FormRef, "KW"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "", .subrecord = "KWDA"},
        .docs = "Keyword membership on a base record (body: query; head: add/remove).",
    },
    {
        .namespace_ = "form",
        .name = "faction",
        .args = {{ElemType::FormRef, "NPC"}, {ElemType::FormRef, "FAC"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "NPC_", .subrecord = "SNAM"},
        .docs = "Faction membership on an NPC base record.",
    },
    {
        .namespace_ = "form",
        .name = "gold_value",
        .args = {{ElemType::FormRef, "F"}, {ElemType::Int, "N"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "", .subrecord = "DATA"},
        .docs = "Gold value of an item.",
    },
    {
        .namespace_ = "form",
        .name = "name",
        .args = {{ElemType::FormRef, "F"}, {ElemType::String, "S"}},
        .arg_count = 2,
        .type = {TypeCtor::Scalar, ElemType::String},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "", .subrecord = "FULL"},
        .docs = "Display name.",
    },
    //   from data/relations/form/weapon.yaml
    {
        .namespace_ = "form",
        .name = "weapon",
        .args = {{ElemType::FormRef, "F"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "WEAP", .subrecord = ""},
        .docs = "True when F is a weapon base record.",
    },
    {
        .namespace_ = "form",
        .name = "damage",
        .args = {{ElemType::FormRef, "W"}, {ElemType::Int, "N"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Int},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "WEAP", .subrecord = "DNAM"},
        .docs = "Weapon base damage (registered via form_model.h from DATA@8).",
    },
    {
        .namespace_ = "form",
        .name = "speed",
        .args = {{ElemType::FormRef, "W"}, {ElemType::Float, "V"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Float},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "WEAP", .subrecord = "DNAM", .extract = EspExtract::PackedField, .offset = 4, .read_as = EspReadType::Float32},
        .docs = "Weapon swing speed multiplier (1.0 = normal).",
    },
    {
        .namespace_ = "form",
        .name = "reach",
        .args = {{ElemType::FormRef, "W"}, {ElemType::Float, "V"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Float},
        .source = RelationSourceKind::Static,
        .esp_source = {.record_type = "WEAP", .subrecord = "DNAM", .extract = EspExtract::PackedField, .offset = 8, .read_as = EspReadType::Float32},
        .docs = "Weapon reach multiplier (1.0 = normal).",
    },
    // ── ref/* ──
    //   from data/relations/ref/actor.yaml
    {
        .namespace_ = "ref",
        .name = "is_dead",
        .args = {{ElemType::FormRef, "R"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadIsDead,
        .docs = "True when R is an actor that is currently dead.",
    },
    {
        .namespace_ = "ref",
        .name = "in_combat",
        .args = {{ElemType::FormRef, "R"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadInCombat,
        .docs = "True when R is an actor currently in combat state.",
    },
    {
        .namespace_ = "ref",
        .name = "health",
        .args = {{ElemType::FormRef, "R"}, {ElemType::Float, "H"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::Float},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadHealth,
        .docs = "Current health value for an actor reference (not max health).",
    },
    {
        .namespace_ = "ref",
        .name = "magicka",
        .args = {{ElemType::FormRef, "R"}, {ElemType::Float, "M"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::Float},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadMagicka,
        .docs = "Current magicka value for an actor reference.",
    },
    {
        .namespace_ = "ref",
        .name = "stamina",
        .args = {{ElemType::FormRef, "R"}, {ElemType::Float, "S"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::Float},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadStamina,
        .docs = "Current stamina value for an actor reference.",
    },
    {
        .namespace_ = "ref",
        .name = "level",
        .args = {{ElemType::FormRef, "R"}, {ElemType::Int, "L"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::Int},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadLevel,
        .docs = "Current (possibly leveled) level of an actor reference. May differ from form/base_level when the actor was auto-leveled.",
    },
    {
        .namespace_ = "ref",
        .name = "equipped_weapon",
        .args = {{ElemType::FormRef, "ACTOR"}, {ElemType::FormRef, "WEAP"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadEquippedWeapon,
        .docs = "Weapon currently held in ACTOR's right (main) hand. Returns the base weapon FormID, not a reference.",
    },
    {
        .namespace_ = "ref",
        .name = "equipped_weapon_left",
        .args = {{ElemType::FormRef, "ACTOR"}, {ElemType::FormRef, "WEAP"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadEquippedWeaponLeft,
        .docs = "Weapon or shield currently held in ACTOR's left (off) hand.",
    },
    {
        .namespace_ = "ref",
        .name = "equipped_spell_left",
        .args = {{ElemType::FormRef, "ACTOR"}, {ElemType::FormRef, "SPELL"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadEquippedSpellLeft,
        .docs = "Spell currently readied in ACTOR's left hand.",
    },
    {
        .namespace_ = "ref",
        .name = "equipped_spell_right",
        .args = {{ElemType::FormRef, "ACTOR"}, {ElemType::FormRef, "SPELL"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadEquippedSpellRight,
        .docs = "Spell currently readied in ACTOR's right hand.",
    },
    {
        .namespace_ = "ref",
        .name = "equipped_armor",
        .args = {{ElemType::FormRef, "ACTOR"}, {ElemType::FormRef, "ARMO"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadEquippedArmor,
        .docs = "Armor pieces currently worn by ACTOR. One fact per equipped piece.",
    },
    {
        .namespace_ = "ref",
        .name = "inventory_item",
        .args = {{ElemType::FormRef, "ACTOR"}, {ElemType::FormRef, "ITEM"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadInventoryItem,
        .docs = "Items currently in ACTOR's inventory (base-form FormIDs; counts and individual ref instances aren't exposed here).",
    },
    //   from data/relations/ref/item.yaml
    {
        .namespace_ = "ref",
        .name = "worn_by",
        .args = {{ElemType::FormRef, "ITEM"}, {ElemType::FormRef, "ACTOR"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadWornBy,
        .docs = "The actor currently wearing or wielding this item reference, if any. Inverse of ref/equipped_armor / ref/equipped_weapon.",
    },
    {
        .namespace_ = "ref",
        .name = "container",
        .args = {{ElemType::FormRef, "ITEM"}, {ElemType::FormRef, "OWNER"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadContainer,
        .docs = "The container or actor currently holding this item reference. Distinct from worn_by — an item can be carried but not equipped.",
    },
    {
        .namespace_ = "ref",
        .name = "is_equipped",
        .args = {{ElemType::FormRef, "ITEM"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadIsEquipped,
        .docs = "True when this item reference is currently equipped on some actor.",
    },
    {
        .namespace_ = "ref",
        .name = "is_stolen",
        .args = {{ElemType::FormRef, "ITEM"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadIsStolen,
        .docs = "True when this item reference has the stolen flag set.",
    },
    //   from data/relations/ref/shared.yaml
    {
        .namespace_ = "ref",
        .name = "base_form",
        .args = {{ElemType::FormRef, "R"}, {ElemType::FormRef, "F"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadBaseForm,
        .docs = "Bridge from a live placed reference to its base record. This is the primary join used to carry a reference over into form/* queries.",
    },
    {
        .namespace_ = "ref",
        .name = "current_location",
        .args = {{ElemType::FormRef, "R"}, {ElemType::FormRef, "LOC"}},
        .arg_count = 2,
        .type = {TypeCtor::Const, ElemType::FormRef},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadCurrentLocation,
        .docs = "The Location record this reference is currently in (nearest parent Location).",
    },
    {
        .namespace_ = "ref",
        .name = "keyword",
        .args = {{ElemType::FormRef, "R"}, {ElemType::FormRef, "KW"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Handler,
        .apply_handler = HandlerId::RefAddKeyword,
        .retract_handler = HandlerId::RefRemoveKeyword,
        .docs = "Keywords added to a specific reference at runtime (distinct from its base form's keywords).",
    },
    {
        .namespace_ = "ref",
        .name = "is_player",
        .args = {{ElemType::FormRef, "R"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadIsPlayer,
        .docs = "True when R is the player character.",
    },
    {
        .namespace_ = "ref",
        .name = "is_npc",
        .args = {{ElemType::FormRef, "R"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadIsNpc,
        .docs = "True when R's base form is an NPC (actor base).",
    },
    {
        .namespace_ = "ref",
        .name = "is_weapon",
        .args = {{ElemType::FormRef, "R"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadIsWeapon,
        .docs = "True when R's base form is a WEAP record.",
    },
    {
        .namespace_ = "ref",
        .name = "is_armor",
        .args = {{ElemType::FormRef, "R"}},
        .arg_count = 1,
        .type = {TypeCtor::Predicate, ElemType::Int},
        .source = RelationSourceKind::Handler,
        .read_handler = HandlerId::RefReadIsArmor,
        .docs = "True when R's base form is an ARMO record.",
    },
    // ── player/* ──
    //   from data/relations/player.yaml
    {
        .namespace_ = "player",
        .name = "gold",
        .args = {{ElemType::FormRef, "P"}, {ElemType::Int, "N"}},
        .arg_count = 2,
        .type = {TypeCtor::Countable, ElemType::Int},
        .source = RelationSourceKind::Handler,
        .apply_handler = HandlerId::PlayerAddGold,
        .docs = "Player gold count (additive delta via 'add').",
    },
    {
        .namespace_ = "player",
        .name = "notification",
        .args = {{ElemType::FormRef, "P"}, {ElemType::String, "S"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::String},
        .source = RelationSourceKind::Handler,
        .apply_handler = HandlerId::PlayerShowNotification,
        .docs = "Queue a UI notification string.",
    },
    // ── world/* ──
    //   from data/relations/world.yaml
    {
        .namespace_ = "world",
        .name = "time_of_day",
        .args = {{ElemType::Float, "T"}},
        .arg_count = 1,
        .type = {TypeCtor::Const, ElemType::Float},
        .source = RelationSourceKind::Hook,
        .hook = {.hook_name = "OnTimeOfDayChanged", .kind = HookSpec::Kind::State},
        .docs = "Current in-game hour 0..24.",
    },
    // ── event/* ──
    //   from data/relations/event.yaml
    {
        .namespace_ = "event",
        .name = "entered_location",
        .args = {{ElemType::FormRef, "R"}, {ElemType::FormRef, "LOC"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Event,
        .hook = {.hook_name = "OnLocationChange", .kind = HookSpec::Kind::Edge},
        .docs = "Fires when a reference enters a new location.",
    },
    {
        .namespace_ = "event",
        .name = "combat_state_changed",
        .args = {{ElemType::FormRef, "R"}, {ElemType::Int, "STATE"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::Int},
        .source = RelationSourceKind::Event,
        .hook = {.hook_name = "OnCombatStateChanged", .kind = HookSpec::Kind::Edge},
        .docs = "Fires on combat state transitions.",
    },
    {
        .namespace_ = "event",
        .name = "killed",
        .args = {{ElemType::FormRef, "VICTIM"}, {ElemType::FormRef, "KILLER"}},
        .arg_count = 2,
        .type = {TypeCtor::List, ElemType::FormRef},
        .source = RelationSourceKind::Event,
        .hook = {.hook_name = "OnActorKilled", .kind = HookSpec::Kind::Edge},
        .docs = "Fires when an actor reference is killed. VICTIM is the actor that died; KILLER is the actor that dealt the killing blow.",
    },
};

const size_t kRelationCount = sizeof(kRelations) / sizeof(kRelations[0]);

static_assert(validate_all(kRelations, sizeof(kRelations) / sizeof(kRelations[0])),
              "kRelations fails validation — see helper checks");

} // namespace mora::model
