//! Per-scenario golden tests. The `#[test]` functions below are
//! generated by `build.rs` from the scenario directories under
//! `tests/golden-data/expected/`. Each calls `run_golden_scenario(name)`,
//! which:
//!
//!   1. Skips with a diagnostic if `MORA_SKYRIM_DATA` is unset.
//!   2. Re-hashes every ESP under that data dir; skips (not fails) if
//!      the hashes don't match the committed manifest.
//!   3. Parses the scenario INI(s) via `mora-kid::ini::parse_file`.
//!   4. Opens the ESP world via `mora-esp::EspWorld::open`.
//!   5. Runs the distributor.
//!   6. Computes `post_state = vanilla_KWDA ∪ patches` per form.
//!   7. Diffs the post-state against the committed JSONL.
//!
//! Skip-not-fail is intentional: a Skyrim patch, a changed ESP, or an
//! unset env var must not red CI on an unrelated PR.

#![allow(dead_code)]

use std::collections::{BTreeMap, BTreeSet};
use std::io::Read;
use std::path::{Path, PathBuf};

use mora_core::{DeterministicChance, Distributor, FormId, Patch, PatchSink};
use mora_esp::EspWorld;
use mora_kid::distributor::KidDistributor;
use mora_kid::ini::parse_file;

include!(concat!(env!("OUT_DIR"), "/golden_tests.rs"));

fn run_golden_scenario(name: &str) {
    let Some(data_dir) = require_data_dir(name) else {
        return;
    };

    let workspace_root = workspace_root();
    let expected_dir = workspace_root.join("tests/golden-data/expected").join(name);
    let ini_dir = workspace_root.join("tests/golden-data/kid-inis").join(name);

    if !verify_manifest(&expected_dir, &data_dir, name) {
        return;
    }

    // Parse every *_KID.ini in the scenario directory.
    let mut rules = Vec::new();
    let mut groups = Vec::new();
    for entry in std::fs::read_dir(&ini_dir).expect("scenario ini dir") {
        let entry = entry.expect("read_dir entry");
        let path = entry.path();
        let Some(lower) = path
            .file_name()
            .and_then(|n| n.to_str())
            .map(|s| s.to_ascii_lowercase())
        else {
            continue;
        };
        if !(lower.ends_with(".ini") && lower.contains("_kid")) {
            continue;
        }
        let parsed = parse_file(&path).expect("ini parse");
        rules.extend(parsed.rules);
        groups.extend(parsed.exclusive_groups);
    }

    // Scenarios share one canonical committed plugins.txt — all use the
    // runner's /skyrim-base/ vanilla + DLC + CC load order.
    let plugins_txt = workspace_root.join("tests/golden-data/plugins.txt");
    let world = EspWorld::open(&data_dir, &plugins_txt).expect("open world");

    let chance = DeterministicChance::kid_compatible();
    let distributor = KidDistributor::new(rules).with_exclusive_groups(groups);
    let mut sink = PatchSink::new();
    distributor
        .lower(&world, &chance, &mut sink)
        .expect("lower");
    let patch_file = sink.finalize();

    let (actual_weapons, actual_armors) = compute_post_state(&world, &patch_file.patches);
    let expected_weapons = load_jsonl(&expected_dir.join("weapons.jsonl"));
    let expected_armors = load_jsonl(&expected_dir.join("armors.jsonl"));

    diff_or_panic(name, "weapons", &actual_weapons, &expected_weapons);
    diff_or_panic(name, "armors", &actual_armors, &expected_armors);
}

fn require_data_dir(scenario: &str) -> Option<PathBuf> {
    match std::env::var("MORA_SKYRIM_DATA") {
        Ok(v) => {
            let p = PathBuf::from(v);
            if !p.is_dir() {
                eprintln!(
                    "skipping golden {scenario}: MORA_SKYRIM_DATA points at {} which is not a directory",
                    p.display()
                );
                return None;
            }
            Some(p)
        }
        Err(_) => {
            eprintln!(
                "skipping golden {scenario}: set MORA_SKYRIM_DATA to a Skyrim Data dir matching the scenario's manifest"
            );
            None
        }
    }
}

/// Returns `true` if every ESP in the manifest matches the data dir.
/// Returns `false` (skip, not fail) if the manifest is absent, invalid,
/// or if any hash mismatches — the local Skyrim install has drifted.
fn verify_manifest(expected_dir: &Path, data_dir: &Path, scenario: &str) -> bool {
    let manifest_path = expected_dir.join("manifest.json");
    let Ok(bytes) = std::fs::read_to_string(&manifest_path) else {
        eprintln!(
            "skipping golden {scenario}: no manifest.json at {}",
            manifest_path.display()
        );
        return false;
    };
    let Ok(manifest): Result<serde_json::Value, _> = serde_json::from_str(&bytes) else {
        eprintln!("skipping golden {scenario}: manifest.json is not valid JSON");
        return false;
    };
    let Some(expected_hashes) = manifest.get("esp_hashes").and_then(|v| v.as_object()) else {
        eprintln!("skipping golden {scenario}: manifest has no esp_hashes");
        return false;
    };
    // Check every ESP in the manifest against the data dir.
    for (name, expected_hash) in expected_hashes {
        let expected_hash = expected_hash.as_str().unwrap_or("");
        let file = data_dir.join(name);
        if !file.is_file() {
            eprintln!(
                "skipping golden {scenario}: manifest references {name} which is absent in data dir"
            );
            return false;
        }
        let actual = hash_file_sha256(&file).unwrap_or_default();
        if actual != expected_hash {
            eprintln!(
                "skipping golden {scenario}: {name} hash mismatch — expected {expected_hash}, got {actual}"
            );
            return false;
        }
    }
    true
}

fn hash_file_sha256(path: &Path) -> std::io::Result<String> {
    use sha2::{Digest, Sha256};
    let f = std::fs::File::open(path)?;
    let mut r = std::io::BufReader::new(f);
    let mut h = Sha256::new();
    let mut buf = [0u8; 64 * 1024];
    loop {
        let n = r.read(&mut buf)?;
        if n == 0 {
            break;
        }
        h.update(&buf[..n]);
    }
    Ok(format!("{:x}", h.finalize()))
}

fn compute_post_state(
    world: &EspWorld,
    patches: &[Patch],
) -> (
    BTreeMap<FormId, BTreeSet<FormId>>,
    BTreeMap<FormId, BTreeSet<FormId>>,
) {
    let mut weapons: BTreeMap<FormId, BTreeSet<FormId>> = BTreeMap::new();
    let mut armors: BTreeMap<FormId, BTreeSet<FormId>> = BTreeMap::new();

    for (fid, w) in world.weapons().flatten() {
        let set = weapons.entry(fid).or_default();
        for kw in &w.keywords {
            set.insert(*kw);
        }
    }
    for (fid, a) in world.armors().flatten() {
        let set = armors.entry(fid).or_default();
        for kw in &a.keywords {
            set.insert(*kw);
        }
    }

    for patch in patches {
        match patch {
            Patch::AddKeyword { target, keyword } => {
                if let Some(set) = weapons.get_mut(target) {
                    set.insert(*keyword);
                } else if let Some(set) = armors.get_mut(target) {
                    set.insert(*keyword);
                }
            }
        }
    }

    // Drop empty entries so "omitted" and "empty" compare equal.
    weapons.retain(|_, v| !v.is_empty());
    armors.retain(|_, v| !v.is_empty());

    (weapons, armors)
}

fn load_jsonl(path: &Path) -> BTreeMap<FormId, BTreeSet<FormId>> {
    let mut out = BTreeMap::new();
    let Ok(content) = std::fs::read_to_string(path) else {
        return out;
    };
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let value: serde_json::Value = match serde_json::from_str(line) {
            Ok(v) => v,
            Err(_) => continue,
        };
        let form_hex = value.get("form").and_then(|v| v.as_str()).unwrap_or("");
        let form_raw = parse_hex_form(form_hex);
        let Some(form) = form_raw else { continue };
        let mut set = BTreeSet::new();
        if let Some(arr) = value.get("kws").and_then(|v| v.as_array()) {
            for kw in arr {
                if let Some(kw_hex) = kw.as_str()
                    && let Some(k) = parse_hex_form(kw_hex)
                {
                    set.insert(k);
                }
            }
        }
        out.insert(form, set);
    }
    out
}

fn parse_hex_form(s: &str) -> Option<FormId> {
    let s = s.strip_prefix("0x").unwrap_or(s);
    u32::from_str_radix(s, 16).ok().map(FormId)
}

fn diff_or_panic(
    scenario: &str,
    which: &str,
    actual: &BTreeMap<FormId, BTreeSet<FormId>>,
    expected: &BTreeMap<FormId, BTreeSet<FormId>>,
) {
    if actual == expected {
        return;
    }
    let mut differences = Vec::new();
    for key in actual
        .keys()
        .chain(expected.keys())
        .collect::<BTreeSet<_>>()
    {
        let a = actual.get(key);
        let e = expected.get(key);
        if a != e {
            let a_set: BTreeSet<FormId> = a.cloned().unwrap_or_default();
            let e_set: BTreeSet<FormId> = e.cloned().unwrap_or_default();
            let missing: Vec<_> = e_set.difference(&a_set).copied().collect();
            let extra: Vec<_> = a_set.difference(&e_set).copied().collect();
            differences.push(format!(
                "  form 0x{:08x}: missing {:?}, extra {:?}",
                key.0, missing, extra
            ));
            if differences.len() >= 20 {
                differences.push("  (first 20 divergences only)".to_string());
                break;
            }
        }
    }
    panic!(
        "scenario {scenario} [{which}] diverges from golden:\n{}",
        differences.join("\n")
    );
}

fn workspace_root() -> PathBuf {
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    PathBuf::from(manifest_dir)
        .parent()
        .and_then(|p| p.parent())
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| PathBuf::from(manifest_dir))
}
