; NPC combat enhancements
filterByFactions=BanditFaction:spellsToAdd=FireBolt,Flames
filterByKeywordsOr=ActorTypeVampire,ActorTypeUndead:perksToAdd=NightEye
levelRange=30~100:keywordsToAdd=EliteCombatant
